apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
kind: KamajiControlPlane
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: dev-cluster
    cni: canal
  name: dev-cluster
spec:
  addons:
    coreDNS: {}
    konnectivity: {}
    kubeProxy: {}
  dataStoreName: default
  kubelet:
    cgroupfs: systemd
    preferredAddressTypes:
      - InternalIP
      - ExternalIP
      - Hostname
  network:
    serviceAddress: 10.69.1.138
    serviceAnnotations:
      kube-vip.io/loadbalancerIPs: 10.69.1.138
    serviceLabels:
      cluster.x-k8s.io/cluster-name: dev-cluster
    serviceType: LoadBalancer
  replicas: 1
  version: v1.29.6
