---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-cluster
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  sources:
    # Helm chart source
    - repoURL: https://clastix.github.io/charts
      chart: capi-kamaji-proxmox
      targetRevision: 0.0.4
      helm:
        valueFiles:
          - $values/cluster-api/dev-cluster/values.yaml
    # Values from git repository
    - repoURL: https://github.com/phuchoang2603/self-host.git
      targetRevision: main
      ref: values
    # Git source for additional manifests
    - repoURL: "https://github.com/phuchoang2603/self-host.git"
      targetRevision: main
      path: cluster-api/dev-cluster/manifests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
