---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kamaji
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kamaji-system
  project: default
  source:
    repoURL: https://clastix.github.io/charts
    chart: kamaji
    targetRevision: 0.0.0+latest
    helm:
      values: |
        image:
          tag: edge-25.11.5

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
