apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxCluster
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: rke2-proxmox
  name: rke2-proxmox
  namespace: default
spec:
  allowedNodes:
    - pve
    - pve2
    - pve3
  credentialsRef:
    name: proxmox-credentials
    namespace: default
  dnsServers:
    - 10.69.0.1
    - 1.1.1.1
  ipv4Config:
    addresses:
      - 10.69.1.139
    gateway: 10.69.0.1
    prefix: 16
  schedulerHints:
    memoryAdjustment: 0
