apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxMachineTemplate
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: rke2-proxmox
  name: rke2-proxmox-worker
  namespace: default
spec:
  template:
    spec:
      allowedNodes:
        - pve
        - pve2
        - pve3
      disks:
        bootVolume:
          disk: scsi0
          sizeGb: 50
      format: qcow2
      full: true
      memoryMiB: 2048
      network:
        default:
          bridge: vmbr1
          dnsServers:
            - 10.69.0.1
            - 1.1.1.1
          ipv4PoolRef:
            apiGroup: ipam.cluster.x-k8s.io
            kind: InClusterIPPool
            name: rke2-proxmox-ipam-pool
          model: virtio
      numCores: 2
      numSockets: 1
      pool: truenas
      sourceNode: pve
      storage: truenas
      templateID: 100
